TrajectoryPlannerROS:
  max_vel_x: 0.05
  min_vel_x: 0.01
  max_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.02

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
  y_vels: [-0.05,-0.01,0.01,0.05]
