obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: .32
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: /kinect_depth_frame, data_type: LaserScan, topic: /scan , marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: /kinect_depth_frame, data_type: PointCloud, topic: camera/depth/points, marking: true, clearing: true}

