//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the hardware_interface package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __hardware_interface__HARDWARE_INTERFACE_PARAMSCONFIG_H__
#define __hardware_interface__HARDWARE_INTERFACE_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace hardware_interface
{
  class hardware_interface_paramsConfigStatics;
  
  class hardware_interface_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(hardware_interface_paramsConfig &config, const hardware_interface_paramsConfig &max, const hardware_interface_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const hardware_interface_paramsConfig &config1, const hardware_interface_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, hardware_interface_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const hardware_interface_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, hardware_interface_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const hardware_interface_paramsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T hardware_interface_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (hardware_interface_paramsConfig::* field);

      virtual void clamp(hardware_interface_paramsConfig &config, const hardware_interface_paramsConfig &max, const hardware_interface_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const hardware_interface_paramsConfig &config1, const hardware_interface_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, hardware_interface_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const hardware_interface_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, hardware_interface_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const hardware_interface_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 15 "../cfg/hardware_interface.cfg"
      double watchdog_timeout;
//#line 16 "../cfg/hardware_interface.cfg"
      double max_speed;
//#line 17 "../cfg/hardware_interface.cfg"
      double min_speed;
//#line 18 "../cfg/hardware_interface.cfg"
      double motor_res;
//#line 19 "../cfg/hardware_interface.cfg"
      double base_radius;
//#line 20 "../cfg/hardware_interface.cfg"
      double wheel_radius;
//#line 21 "../cfg/hardware_interface.cfg"
      bool tilt_enable;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("hardware_interface_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const hardware_interface_paramsConfig &__max__ = __getMax__();
      const hardware_interface_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const hardware_interface_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const hardware_interface_paramsConfig &__getDefault__();
    static const hardware_interface_paramsConfig &__getMax__();
    static const hardware_interface_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const hardware_interface_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void hardware_interface_paramsConfig::ParamDescription<std::string>::clamp(hardware_interface_paramsConfig &config, const hardware_interface_paramsConfig &max, const hardware_interface_paramsConfig &min) const
  {
    return;
  }

  class hardware_interface_paramsConfigStatics
  {
    friend class hardware_interface_paramsConfig;
    
    hardware_interface_paramsConfigStatics()
    {
//#line 15 "../cfg/hardware_interface.cfg"
      __min__.watchdog_timeout = 0.0;
//#line 15 "../cfg/hardware_interface.cfg"
      __max__.watchdog_timeout = 10.0;
//#line 15 "../cfg/hardware_interface.cfg"
      __default__.watchdog_timeout = 5.0;
//#line 15 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("watchdog_timeout", "double", 0, "The time in seconds between watchdog timeouts", "", &hardware_interface_paramsConfig::watchdog_timeout)));
//#line 16 "../cfg/hardware_interface.cfg"
      __min__.max_speed = 0.0;
//#line 16 "../cfg/hardware_interface.cfg"
      __max__.max_speed = 5.0;
//#line 16 "../cfg/hardware_interface.cfg"
      __default__.max_speed = 1.0;
//#line 16 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("max_speed", "double", 0, "Top motor speed in ticks/second", "", &hardware_interface_paramsConfig::max_speed)));
//#line 17 "../cfg/hardware_interface.cfg"
      __min__.min_speed = 0.0;
//#line 17 "../cfg/hardware_interface.cfg"
      __max__.min_speed = 5.0;
//#line 17 "../cfg/hardware_interface.cfg"
      __default__.min_speed = 1.0;
//#line 17 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("min_speed", "double", 0, "Stop motor threshold speed in ticks/second", "", &hardware_interface_paramsConfig::min_speed)));
//#line 18 "../cfg/hardware_interface.cfg"
      __min__.motor_res = 0.0;
//#line 18 "../cfg/hardware_interface.cfg"
      __max__.motor_res = 100.0;
//#line 18 "../cfg/hardware_interface.cfg"
      __default__.motor_res = 200.0;
//#line 18 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("motor_res", "double", 0, "Motor resolutin in tics/revolution", "", &hardware_interface_paramsConfig::motor_res)));
//#line 19 "../cfg/hardware_interface.cfg"
      __min__.base_radius = 0.0;
//#line 19 "../cfg/hardware_interface.cfg"
      __max__.base_radius = 1.0;
//#line 19 "../cfg/hardware_interface.cfg"
      __default__.base_radius = 0.25;
//#line 19 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("base_radius", "double", 0, "Radius of the robot base in meters", "", &hardware_interface_paramsConfig::base_radius)));
//#line 20 "../cfg/hardware_interface.cfg"
      __min__.wheel_radius = 0.0;
//#line 20 "../cfg/hardware_interface.cfg"
      __max__.wheel_radius = 1.0;
//#line 20 "../cfg/hardware_interface.cfg"
      __default__.wheel_radius = 0.1016;
//#line 20 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<double>("wheel_radius", "double", 0, "Radius of the robot wheels in meters", "", &hardware_interface_paramsConfig::wheel_radius)));
//#line 21 "../cfg/hardware_interface.cfg"
      __min__.tilt_enable = 0;
//#line 21 "../cfg/hardware_interface.cfg"
      __max__.tilt_enable = 1;
//#line 21 "../cfg/hardware_interface.cfg"
      __default__.tilt_enable = 0;
//#line 21 "../cfg/hardware_interface.cfg"
      __param_descriptions__.push_back(hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new hardware_interface_paramsConfig::ParamDescription<bool>("tilt_enable", "bool", 0, "Enable control of kintect tilt angle", "", &hardware_interface_paramsConfig::tilt_enable)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    hardware_interface_paramsConfig __max__;
    hardware_interface_paramsConfig __min__;
    hardware_interface_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const hardware_interface_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static hardware_interface_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &hardware_interface_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const hardware_interface_paramsConfig &hardware_interface_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const hardware_interface_paramsConfig &hardware_interface_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const hardware_interface_paramsConfig &hardware_interface_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr> &hardware_interface_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const hardware_interface_paramsConfigStatics *hardware_interface_paramsConfig::__get_statics__()
  {
    const static hardware_interface_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = hardware_interface_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __HARDWARE_INTERFACE_PARAMSRECONFIGURATOR_H__
