//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the turtlebot_360_hardware_interface package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __turtlebot_360_hardware_interface__TURTLEBOT_360_HARDWARE_INTERFACE_PARAMSCONFIG_H__
#define __turtlebot_360_hardware_interface__TURTLEBOT_360_HARDWARE_INTERFACE_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace turtlebot_360_hardware_interface
{
  class turtlebot_360_hardware_interface_paramsConfigStatics;
  
  class turtlebot_360_hardware_interface_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(turtlebot_360_hardware_interface_paramsConfig &config, const turtlebot_360_hardware_interface_paramsConfig &max, const turtlebot_360_hardware_interface_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const turtlebot_360_hardware_interface_paramsConfig &config1, const turtlebot_360_hardware_interface_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, turtlebot_360_hardware_interface_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const turtlebot_360_hardware_interface_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, turtlebot_360_hardware_interface_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const turtlebot_360_hardware_interface_paramsConfig &config) const = 0;
      virtual void getValue(const turtlebot_360_hardware_interface_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T turtlebot_360_hardware_interface_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (turtlebot_360_hardware_interface_paramsConfig::* field);

      virtual void clamp(turtlebot_360_hardware_interface_paramsConfig &config, const turtlebot_360_hardware_interface_paramsConfig &max, const turtlebot_360_hardware_interface_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const turtlebot_360_hardware_interface_paramsConfig &config1, const turtlebot_360_hardware_interface_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, turtlebot_360_hardware_interface_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const turtlebot_360_hardware_interface_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, turtlebot_360_hardware_interface_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const turtlebot_360_hardware_interface_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const turtlebot_360_hardware_interface_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, turtlebot_360_hardware_interface_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, turtlebot_360_hardware_interface_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(turtlebot_360_hardware_interface_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("watchdog_timeout"==(*i)->name){watchdog_timeout = boost::any_cast<double>(val);}
        if("max_accel"==(*i)->name){max_accel = boost::any_cast<double>(val);}
        if("max_speed"==(*i)->name){max_speed = boost::any_cast<double>(val);}
        if("min_speed"==(*i)->name){min_speed = boost::any_cast<double>(val);}
        if("motor_res"==(*i)->name){motor_res = boost::any_cast<double>(val);}
        if("base_radius"==(*i)->name){base_radius = boost::any_cast<double>(val);}
        if("wheel_radius"==(*i)->name){wheel_radius = boost::any_cast<double>(val);}
        if("motor1_i2c_addr"==(*i)->name){motor1_i2c_addr = boost::any_cast<int>(val);}
        if("motor2_i2c_addr"==(*i)->name){motor2_i2c_addr = boost::any_cast<int>(val);}
        if("motor3_i2c_addr"==(*i)->name){motor3_i2c_addr = boost::any_cast<int>(val);}
        if("tilt_enable"==(*i)->name){tilt_enable = boost::any_cast<bool>(val);}
        if("serial_port"==(*i)->name){serial_port = boost::any_cast<std::string>(val);}
      }
    }

    double watchdog_timeout;
double max_accel;
double max_speed;
double min_speed;
double motor_res;
double base_radius;
double wheel_radius;
int motor1_i2c_addr;
int motor2_i2c_addr;
int motor3_i2c_addr;
bool tilt_enable;
std::string serial_port;

    bool state;
    std::string name;

    
}groups;



//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double watchdog_timeout;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double max_accel;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double max_speed;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double min_speed;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double motor_res;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double base_radius;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double wheel_radius;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int motor1_i2c_addr;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int motor2_i2c_addr;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int motor3_i2c_addr;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool tilt_enable;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      std::string serial_port;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("turtlebot_360_hardware_interface_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const turtlebot_360_hardware_interface_paramsConfig &__max__ = __getMax__();
      const turtlebot_360_hardware_interface_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const turtlebot_360_hardware_interface_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const turtlebot_360_hardware_interface_paramsConfig &__getDefault__();
    static const turtlebot_360_hardware_interface_paramsConfig &__getMax__();
    static const turtlebot_360_hardware_interface_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const turtlebot_360_hardware_interface_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void turtlebot_360_hardware_interface_paramsConfig::ParamDescription<std::string>::clamp(turtlebot_360_hardware_interface_paramsConfig &config, const turtlebot_360_hardware_interface_paramsConfig &max, const turtlebot_360_hardware_interface_paramsConfig &min) const
  {
    return;
  }

  class turtlebot_360_hardware_interface_paramsConfigStatics
  {
    friend class turtlebot_360_hardware_interface_paramsConfig;
    
    turtlebot_360_hardware_interface_paramsConfigStatics()
    {
turtlebot_360_hardware_interface_paramsConfig::GroupDescription<turtlebot_360_hardware_interface_paramsConfig::DEFAULT, turtlebot_360_hardware_interface_paramsConfig> Default("Default", "", 0, 0, true, &turtlebot_360_hardware_interface_paramsConfig::groups);
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.watchdog_timeout = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.watchdog_timeout = 10.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.watchdog_timeout = 5.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("watchdog_timeout", "double", 0, "The time in seconds between watchdog timeouts", "", &turtlebot_360_hardware_interface_paramsConfig::watchdog_timeout)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("watchdog_timeout", "double", 0, "The time in seconds between watchdog timeouts", "", &turtlebot_360_hardware_interface_paramsConfig::watchdog_timeout)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.max_accel = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.max_accel = 800.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.max_accel = 15.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("max_accel", "double", 0, "Top motor acceleration in (ticks/second)/second", "", &turtlebot_360_hardware_interface_paramsConfig::max_accel)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("max_accel", "double", 0, "Top motor acceleration in (ticks/second)/second", "", &turtlebot_360_hardware_interface_paramsConfig::max_accel)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.max_speed = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.max_speed = 800.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.max_speed = 80.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("max_speed", "double", 0, "Top motor speed in ticks/second", "", &turtlebot_360_hardware_interface_paramsConfig::max_speed)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("max_speed", "double", 0, "Top motor speed in ticks/second", "", &turtlebot_360_hardware_interface_paramsConfig::max_speed)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.min_speed = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.min_speed = 800.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.min_speed = 5.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("min_speed", "double", 0, "Stop motor threshold speed in ticks/second", "", &turtlebot_360_hardware_interface_paramsConfig::min_speed)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("min_speed", "double", 0, "Stop motor threshold speed in ticks/second", "", &turtlebot_360_hardware_interface_paramsConfig::min_speed)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.motor_res = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.motor_res = 500.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.motor_res = 200.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("motor_res", "double", 0, "Motor resolution in ticks/revolution", "", &turtlebot_360_hardware_interface_paramsConfig::motor_res)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("motor_res", "double", 0, "Motor resolution in ticks/revolution", "", &turtlebot_360_hardware_interface_paramsConfig::motor_res)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.base_radius = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.base_radius = 1.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.base_radius = 0.177;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("base_radius", "double", 0, "Radius of the robot base in meters", "", &turtlebot_360_hardware_interface_paramsConfig::base_radius)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("base_radius", "double", 0, "Radius of the robot base in meters", "", &turtlebot_360_hardware_interface_paramsConfig::base_radius)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.wheel_radius = 0.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.wheel_radius = 1.0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.wheel_radius = 0.0508;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("wheel_radius", "double", 0, "Radius of the robot wheels in meters", "", &turtlebot_360_hardware_interface_paramsConfig::wheel_radius)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<double>("wheel_radius", "double", 0, "Radius of the robot wheels in meters", "", &turtlebot_360_hardware_interface_paramsConfig::wheel_radius)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.motor1_i2c_addr = 1;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.motor1_i2c_addr = 127;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.motor1_i2c_addr = 3;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor1_i2c_addr", "int", 0, "I2C address of motor 1 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor1_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor1_i2c_addr", "int", 0, "I2C address of motor 1 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor1_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.motor2_i2c_addr = 1;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.motor2_i2c_addr = 127;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.motor2_i2c_addr = 1;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor2_i2c_addr", "int", 0, "I2C address of motor 2 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor2_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor2_i2c_addr", "int", 0, "I2C address of motor 2 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor2_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.motor3_i2c_addr = 1;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.motor3_i2c_addr = 127;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.motor3_i2c_addr = 2;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor3_i2c_addr", "int", 0, "I2C address of motor 3 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor3_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<int>("motor3_i2c_addr", "int", 0, "I2C address of motor 3 controller", "", &turtlebot_360_hardware_interface_paramsConfig::motor3_i2c_addr)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.tilt_enable = 0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.tilt_enable = 1;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.tilt_enable = 0;
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<bool>("tilt_enable", "bool", 0, "Enable control of Kinect tilt angle", "", &turtlebot_360_hardware_interface_paramsConfig::tilt_enable)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<bool>("tilt_enable", "bool", 0, "Enable control of Kinect tilt angle", "", &turtlebot_360_hardware_interface_paramsConfig::tilt_enable)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.serial_port = "";
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.serial_port = "";
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.serial_port = "/dev/ttyUSB0";
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<std::string>("serial_port", "str", 0, "Serial port for motor controller", "", &turtlebot_360_hardware_interface_paramsConfig::serial_port)));
//#line 254 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::ParamDescription<std::string>("serial_port", "str", 0, "Serial port for motor controller", "", &turtlebot_360_hardware_interface_paramsConfig::serial_port)));
//#line 228 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 228 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(turtlebot_360_hardware_interface_paramsConfig::AbstractGroupDescriptionConstPtr(new turtlebot_360_hardware_interface_paramsConfig::GroupDescription<turtlebot_360_hardware_interface_paramsConfig::DEFAULT, turtlebot_360_hardware_interface_paramsConfig>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    turtlebot_360_hardware_interface_paramsConfig __max__;
    turtlebot_360_hardware_interface_paramsConfig __min__;
    turtlebot_360_hardware_interface_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const turtlebot_360_hardware_interface_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static turtlebot_360_hardware_interface_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &turtlebot_360_hardware_interface_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const turtlebot_360_hardware_interface_paramsConfig &turtlebot_360_hardware_interface_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const turtlebot_360_hardware_interface_paramsConfig &turtlebot_360_hardware_interface_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const turtlebot_360_hardware_interface_paramsConfig &turtlebot_360_hardware_interface_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractParamDescriptionConstPtr> &turtlebot_360_hardware_interface_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<turtlebot_360_hardware_interface_paramsConfig::AbstractGroupDescriptionConstPtr> &turtlebot_360_hardware_interface_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const turtlebot_360_hardware_interface_paramsConfigStatics *turtlebot_360_hardware_interface_paramsConfig::__get_statics__()
  {
    const static turtlebot_360_hardware_interface_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = turtlebot_360_hardware_interface_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __TURTLEBOT_360_HARDWARE_INTERFACE_PARAMSRECONFIGURATOR_H__
